name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔥 FIX: Force Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Verify Java
        run: |
          java -version
          mvn -version

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Configure Docker
        run: |
          mkdir -p ~/.docker
          echo '{}' > ~/.docker/config.json

      - name: Build Docker image
        run: docker build -t localhost:5000/github-action-argocd:latest .

      - name: Push Docker image
        run: docker push localhost:5000/github-action-argocd:latest